platform :ios, '8.0'
target 'BYXuNiPan' do

pod 'CocoaAsyncSocket'  
pod "MJRefresh"
pod 'AFNetworking'
pod 'SDWebImage'
pod "SVProgressHUD"
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SwipeBack'

pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'



pod 'TZImagePickerController'
pod 'Masonry'
pod 'SocketRocket'
pod 'UMengAnalytics-NO-IDFA'
pod 'TYAttributedLabel'


end
